### ISSUE TITLE
Missing image paths ebook CSS for Luther theme 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-luther#4]
**Description**
Books on the Luther theme cannot be successfully exported as EPUB or MOBI files because image paths for em dashes and asterisks in the Luther ebook CSS cannot be found. 

EPUB and MOBI exports fail validation with the following errors: 

ERROR(RSC-007): /srv/www/textopress.com/releases/20181220184021/web/app/uploads/sites/117/pressbooks/exports/Test-Book-2-1545331802.epub/OEBPS/luther.css(54,3): Referenced resource could not be found in the EPUB.
ERROR(RSC-007): /srv/www/textopress.com/releases/20181220184021/web/app/uploads/sites/117/pressbooks/exports/Test-Book-2-1545331802.epub/OEBPS/luther.css(57,3): Referenced resource could not be found in the EPUB.

**Steps to Reproduce**
1. Apply the Luther theme to any book on Pressbooks (**Appearance > Themes**)
2. Go to **Exports** from the left sidebar menu 
3. Select EPUB and MOBI from the export options and click Export Your Book 
4. See if the "Warning: The export has validation errors. See logs for more details" banner appears at the top of the screen

If you've changed your settings to receive validation logs, you'll be emailed a copy of the error report and will see the "Referenced resource could not be found in the EPUB" message from above. 

**Expected Behavior:** Books on the Luther theme can be exported as EPUB or MOBI files without error. 
**Actual Behavior:** Image paths missing from Luther ebook CSS cuse EPUB and MOBI files to export with validation errors. 

#### Book Info

Book ID: 117
Book URL: http://languagetest.textopress.com/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 12.0.1
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15

#### WordPress Configuration

Network URL: http://textopress.com/
Network Type: Subdomain
Version: 5.0.1
Language: en_US
WP_ENV: staging
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.7.0-dev
Book Theme: Luther
Book Theme Version: 1.8.3
Root Theme: Aldine
Root Theme Version: 1.6.0-dev

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.0
hm-autoloader.php: n/a
telemetry.php: n/a

#### Network Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.7.0-dev
Pressbooks BISAC: 2.0.0
Pressbooks Client Marketing: 1.0.1
Pressbooks LTI Provider: 1.1.2
Pressbooks SELF-e: 1.5.1
Pressbooks Stats: 1.6.2
Pressbooks Whitelabel: 1.3.0
Redis Object Cache: 1.4.1

#### Book Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.7.0-dev
Pressbooks BISAC: 2.0.0
Pressbooks Client Marketing: 1.0.1
Pressbooks LTI Provider: 1.1.2
Pressbooks SELF-e: 1.5.1
Pressbooks Stats: 1.6.2
Pressbooks Whitelabel: 1.3.0
Redis Object Cache: 1.4.1

#### Inactive Plugins

H5P: 1.11.3
Parsedown Party: 1.1.1
Pressbooks BiblioBoard OAuth: 3.0.0
Pressbooks CAS Single Sign-On: 1.1.1
Pressbooks Shibboleth Single Sign-On: 0.0.5
Pressbooks VIP: 5.4.0
TablePress: 1.9.1
WP QuickLaTeX: 3.8.5

#### Server Configuration

PHP Version: 7.1.23-3+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.5.5
Webserver Info: nginx/1.13.6

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 25M
Post Max Size: 25M
Upload Max Filesize: 25M
Time Limit: 120
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
Fixed in https://github.com/pressbooks/pressbooks/pull/1542
